-- What is the most common room type in NYC Airbnb listings?
SELECT room_type, COUNT(*) 
FROM room_types
GROUP BY room_type
ORDER BY 2 DESC;

-- What is the average price of a listing by room type?
SELECT  room_type,
        ROUND(AVG(price),2)
FROM prices p
JOIN room_types r
ON p.listing_id = r.listing_id
GROUP BY room_type
ORDER BY 2 DESC;

-- Which borough has the highest average price per month?
SELECT  borough,
        ROUND(AVG(price),2)
FROM prices
GROUP BY 1
ORDER BY 2 DESC;

-- How many listings of each room type are in each borough?
SELECT  borough,
        room_type,
        COUNT(*)
FROM prices p
JOIN room_types r
ON p.listing_id = r.listing_id
GROUP BY borough, room_type
ORDER BY borough;

-- How many listings in each room type category have a price of over $500 per night?
SELECT  room_type,
        COUNT(*)
FROM prices p
JOIN room_types r
ON p.listing_id = r.listing_id
WHERE price > 500
GROUP BY room_type;

-- What is the distribution of listing prices by neighbourhood?
SELECT  neighbourhood,
        MIN(price),
        MAX(price),
        ROUND(AVG(price),2)
FROM prices
GROUP BY neighbourhood
ORDER BY neighbourhood;

-- What is the distribution of listing prices by borough?
SELECT  borough,
        MIN(price),
        MAX(price),
        ROUND(AVG(price),2)
FROM prices
GROUP BY borough;

-- What is the estimated amount of revenue generated by hosts in each borough?
SELECT  borough,
        SUM(booked_days_365 * price)
FROM prices p
JOIN reviews r
ON p.listing_id = r.listing_id
GROUP BY borough;

-- What is the average price per month for listings in each neighborhood?
SELECT  neighbourhood,
        room_type,
        AVG(price_per_month)
FROM prices p
JOIN room_types r
ON p.listing_id = r.listing_id
GROUP BY neighbourhood, room_type;

-- How many listings have no reviews?
SELECT COUNT(*)
FROM reviews
WHERE number_of_reviews = 0;

-- How do the estimated book days correlate with the price of an Airbnb listing in New York City?
SELECT CORR(price, booked_days_365)
FROM prices p
JOIN reviews r
ON p.listing_id = r.listing_id;

-- What is the average price per room type for listings that have at least 100 reviews and are available more than 200 days a year?
SELECT  room_type,
        AVG(price)
FROM prices p
JOIN reviews r
ON p.listing_id = r.listing_id
JOIN room_types rt
ON r.listing_id = rt.listing_id
WHERE number_of_reviews >= 100 AND availability_365 > 200
GROUP BY room_type;

-- How many hosts have more than one listing, and what's the maximum number of listings by a single host name?