-- What is the most common room type in NYC Airbnb listings?
SELECT room_type, COUNT(*) 
FROM room_types
GROUP BY room_type
ORDER BY 2 DESC;

-- What is the average price of a listing by room type?
SELECT  room_type,
        ROUND(AVG(price),2)
FROM prices p
JOIN room_types r
ON p.listing_id = r.listing_id
GROUP BY room_type
ORDER BY 2 DESC;

-- Which borough has the highest average price per month?
SELECT  borough,
        ROUND(AVG(price),2)
FROM prices
GROUP BY 1
ORDER BY 2 DESC;

-- How many listings of each room type are in each borough?
SELECT  borough,
        room_type,
        COUNT(*)
FROM prices p
JOIN room_types r
ON p.listing_id = r.listing_id
GROUP BY borough, room_type
ORDER BY borough;

-- How many listings in each room type category have a price of over $500 per night?
SELECT  room_type,
        COUNT(*)
FROM prices p
JOIN room_types r
ON p.listing_id = r.listing_id
WHERE price > 500
GROUP BY room_type;

-- What is the distribution of listing prices by neighbourhood?
SELECT  neighbourhood,
        MIN(price),
        MAX(price),
        ROUND(AVG(price),2)
FROM prices
GROUP BY neighbourhood
ORDER BY neighbourhood;

-- What is the distribution of listing prices by borough?
SELECT  borough,
        MIN(price),
        MAX(price),
        ROUND(AVG(price),2)
FROM prices
GROUP BY borough;

-- What is the estimated amount of revenue generated by hosts in each borough?
SELECT  borough,
        SUM(booked_days_365 * price)
FROM prices p
JOIN reviews r
ON p.listing_id = r.listing_id
GROUP BY borough;

-- What is the average price per month for listings in each neighborhood?
SELECT  neighbourhood,
        room_type,
        AVG(price_per_month)
FROM prices p
JOIN room_types r
ON p.listing_id = r.listing_id
GROUP BY neighbourhood, room_type;

-- How many listings have no reviews?
SELECT COUNT(*)
FROM reviews
WHERE number_of_reviews = 0;

-- How do the estimated book days correlate with the price of an Airbnb listing in New York City?
SELECT CORR(price, booked_days_365)
FROM prices p
JOIN reviews r
ON p.listing_id = r.listing_id;

-- What is the average price per room type for listings that have at least 100 reviews and are available more than 200 days a year?
SELECT  room_type,
        AVG(price)
FROM prices p
JOIN reviews r
ON p.listing_id = r.listing_id
JOIN room_types rt
ON r.listing_id = rt.listing_id
WHERE number_of_reviews >= 100 AND availability_365 > 200
GROUP BY room_type;

-- How many hosts have more than one listing, and what's the maximum number of listings by a single host name?
SELECT COUNT(DISTINCT host_name) AS num_hosts,
       MAX(calculated_host_listings_count) AS max_listings
FROM reviews 
WHERE calculated_host_listings_count > 1;

-- Determine the top 5 hosts who have the highest price_per_month for their listings, 
-- considering only hosts who have at least 10 listings.
SELECT host_name, price_per_month, calculated_host_listings_count
FROM (
  SELECT host_name, price_per_month, calculated_host_listings_count,
    ROW_NUMBER() OVER (PARTITION BY host_name ORDER BY price_per_month DESC) AS rn
  FROM prices p
  JOIN reviews r ON p.listing_id = r.listing_id
  WHERE calculated_host_listings_count >= 10
) AS subquery
WHERE rn = 1
ORDER BY price_per_month DESC
LIMIT 5;

-- Find the neighborhood(s) that have the highest variance in listing prices.
SELECT neighbourhood, ROUND(VARIANCE(price),2) AS price_variance
FROM prices
GROUP BY neighbourhood
HAVING VARIANCE(price) IS NOT NULL
ORDER BY price_variance DESC
LIMIT 5;

-- Calculate the average price_per_month for each neighborhood, taking into account only listings 
-- where the host has a minimum_nights value that is higher than the average minimum_nights 
-- value across all listings.
SELECT neighbourhood, ROUND(AVG(price_per_month)::numeric,2)
FROM prices p
JOIN reviews r
ON p.listing_id = r.listing_id
WHERE availability_365 > (SELECT AVG(availability_365) FROM reviews)
GROUP BY neighbourhood
ORDER BY 2 DESC;
